export const announcements = [
  {
    id: 1,
    title: "Surplus Food Collection Drive - Local Restaurants",
    content: "Join our mission to reduce food waste! We're collecting surplus food from participating restaurants in Downtown area. Restaurants can register for daily pickup between 9 PM - 10 PM. Expected surplus: 50-100 meals per restaurant. Help us create a sustainable food distribution network!",
    date: "2024-03-10",
    priority: "high",
    category: "collection",
    read: false,
    location: "Downtown District",
    timeSlot: "9:00 PM - 10:00 PM",
    expectedQuantity: "50-100 meals",
    source: "Local Restaurants",
    coordinator: "Food Rescue Team"
  },
  {
    id: 2,
    title: "Bulk Food Delivery - Central Community Center",
    content: "Scheduled food distribution at Central Community Center. Fresh produce and prepared meals available for community members. Bring your own bags if possible. Priority given to families and elderly residents.",
    date: "2024-03-12",
    priority: "high",
    category: "delivery",
    read: false,
    location: "Central Community Center, 123 Main St",
    timeSlot: "2:00 PM - 4:00 PM",
    expectedQuantity: "300 meal portions",
    source: "Local Farms & Restaurants",
    coordinator: "Distribution Team Alpha"
  },
  {
    id: 3,
    title: "Emergency Food Relief - South District",
    content: "Immediate distribution of excess catering food from Tech Conference. High-quality prepared meals available. Volunteers needed for packaging and distribution. Contact coordinator for participation.",
    date: "2024-03-11",
    priority: "high",
    category: "emergency",
    read: false,
    location: "South District Community Hall",
    timeSlot: "5:30 PM - 7:30 PM",
    expectedQuantity: "200 packaged meals",
    source: "Corporate Event Catering",
    coordinator: "Rapid Response Team"
  },
  {
    id: 4,
    title: "Weekly Grocery Rescue - Supermarket Partners",
    content: "Collection of near-expiry but safe groceries from participating supermarkets. Items include fresh produce, dairy, and bakery products. Volunteers with vehicles needed for pickup and delivery to distribution centers.",
    date: "2024-03-13",
    priority: "medium",
    category: "collection",
    read: true,
    location: "Multiple Supermarket Locations",
    timeSlot: "8:00 PM - 9:30 PM",
    expectedQuantity: "500kg mixed groceries",
    source: "Partner Supermarkets",
    coordinator: "Grocery Rescue Initiative"
  },
  {
    id: 5,
    title: "Restaurant Food Rescue - Night Campaign",
    content: "Evening collection of surplus food from participating restaurants. Professional kitchen standards maintained for food safety. Looking for volunteer drivers with temperature-controlled vehicles.",
    date: "2024-03-14",
    priority: "medium",
    category: "collection",
    read: false,
    location: "West End Restaurant District",
    timeSlot: "10:00 PM - 11:00 PM",
    expectedQuantity: "150-200 portions",
    source: "Partner Restaurants",
    coordinator: "Night Rescue Squad"
  },
  {
    id: 6,
    title: "Food Expiry Alert",
    content: "Your listed food items are nearing their expiry date. Please check and consume or donate them as soon as possible to avoid waste.",
    date: "2024-03-15",
    priority: "high",
    category: "alert",
    read: false,
    location: "Your Pantry",
    timeSlot: "N/A",
    expectedQuantity: "Varies",
    source: "Food Inventory System",
    coordinator: "Pantry Management Team"
  }
];
